### ISSUE TITLE
Trying to understand weird behaviour

### ISSUE THREAD

**Issue by memoakten** [akatz-ai/ComfyUI-AKatz-Nodes#20]
Hey, I just discovered this wonderful custom node and am trying it out!

I read your fantastically thorough notion doc, but there is some behaviour I don't understand. 

1. I noticed that if I want to start transitionining immediately, I put `(0.0, 0, 7)` at the top to start transitioning over 7 frames (~1 sec at 8fps) starting at frame 0, but this skips the first image altogether. See images below

![image](https://github.com/user-attachments/assets/325dc194-d13b-4e86-9515-a5c2dcc9b875)

![image](https://github.com/user-attachments/assets/10d9a848-c417-42be-9226-fe6f9715ccce)

I have to make the transition start at frame 1. Is this expected behaviour?

![image](https://github.com/user-attachments/assets/256788b7-72c4-4236-ac4e-a0f7c905cb29)

![image](https://github.com/user-attachments/assets/40290353-ce86-4cce-b317-2e801811e2da)

2. If I want to hold for 1 sec (8 frames) on each image, including at the start, I put in:
```
(0.0, 8, 7)
(1.0, 24, 7)
(0.0, 40, 7)
```
And this gives expected results
![image](https://github.com/user-attachments/assets/2a7cf9ad-b9c4-47a7-b42e-70e61bf7191c)

But if I start with weight 1 (i.e. hold) with the schedule below, I would expect it to do the same. But it doesn't. It snaps at every switch. Am I misunderstanding something?
```
(1.0, 0, 7)
(0.0, 16, 7)
(1.0, 32, 7)
```
![image](https://github.com/user-attachments/assets/a3ad3c8d-bfc3-4b79-b2dd-a15067ec321e)

P.S. The snaps are because the images switch over at the same time that the transitions start, so I'm not sure how they sync up?
![image](https://github.com/user-attachments/assets/66cf443a-879c-4488-8dba-e70d5b19231a)

**Comment by memoakten** [comment]
Another one. The weights look ok to me, but the video seems to be snapping. Are the image batches switching at wrong times?
Video and PNG with workflow attached. 
(Video is 10fps, so transitions should be 2 seconds). 
```
(0.0, 20, 19)
(1.0, 50, 19)
(0.0, 70, 19)
```
![image](https://github.com/user-attachments/assets/85196ed3-a4a1-4887-bd30-3ce593975d54)

![image](https://github.com/user-attachments/assets/f1adb213-ddd5-4655-991f-a855e8ec99d9)

![ipa_custom_weights_00033](https://github.com/user-attachments/assets/6e026d13-b792-4747-a847-d60775d1af88)

https://github.com/user-attachments/assets/b36f66a3-769f-47ba-964e-983967d4851a

**Comment by akatz-ai** [comment]
Hey memo, thanks for trying out my node pack! And for the detailed write up! Let me try and answer your questions above:
1. It is expected behavior that starting transitions on frame index 0 results in the same image being held for multiple frames, but it's probably not how it _should_ behave moving forward. I wanted a way to specify exactly what the starting weight should be (1.0 by default), so my idea was just to allow users to specify the weight in the schedule at frame 0, so you can have something like:
`(0.0, 0)`
and weights will start at 0.0, while weights_invert start at 1.0. This is also to allow for both IP Adapters to be turned off completely with the input schedule string:
`((0.0, 0.0), 0)`
which will make weights and weights_invert will both start at 0.0.
In hindsight I should have just put that in as a separate parameter instead of overloading the schedule string with that functionality. I'll change that behavior in a future update.

2. The weights in this example seem to be working as expected, as confirmed by the graph image. The weird popping happens (I believe) when the total frame count is not aligned well with the context window of AnimateDiff. The best way I found to make sure there is good alignment and get smoother transitions is to set the frame counts in increments of 8. 
So for example using your provided workflow, when I tried setting 100 as the frame count I got a video like this (lots of popping):

https://github.com/user-attachments/assets/f282be3b-b8b0-44e7-81fc-a0f6f48d1d62

Now if I change nothing else but set the total frame count to 96 instead, I get this video (smoother):

https://github.com/user-attachments/assets/452c0d65-2967-40ba-9f57-4d461cd2dc2a

Likewise with 104 frames:

https://github.com/user-attachments/assets/87c2d6ad-dad0-4f5d-ab89-6ba7e8fa4971

It seems like some models and settings will cause the animation to _hang_ on certain scenes for more or less time, but changing the overall frame count to be a multiple of 8 seems to have a big effect on how smooth the output will be. Hopefully that helps!
(also fyi in case it helps, in your wf I changed the beta_schedule from autoselect to lcm >> sqrt_linear to greatly improve the output quality and avoid the blurriness and noise artifacting. Additionally setting the IPA Batch nodes to use ease-in-out instead of linear can help with smoothness as well)

**Comment by memoakten** [comment]
Hey, the for the response.

Regarding 1.) ok when you explain it like this, it makes sense. I just wasn't expecting that! "_In hindsight I should have just put that in as a separate parameter instead of overloading the schedule string with that functionality_." yea I think an extra widget for this is a good idea.

2.) oh this is very interesting regarding the total number of frames! I will experiment with that thanks. Interestingly, my experience with the weight type, I get more snapping with `ease in-out`, and `linear` gave me best results. Though I imagine this is very dependent on the specific situation, model, prompts, ipadapter images etc. And I also found `lcm avg(sqrt, linear)` to be my fav beta schedule, but again this is very specific.

**Comment by akatz-ai** [comment]
@memo Went ahead and updated the custom node to include a "default_weights" input widget, which allows you to specify the starting weights using a string format like: "1.0, 0.0", or "0.5, 0.5", or even just "1.0" which implies "1.0, 0.0". I also modified the weights string input to allow you to start animations at frame 0 without issue. These changes were pushed as of pr #21 . Using older workflows with this custom node will likely need the custom node to be reset by right clicking on it and hitting "Fix Node(recreate)". Just make sure to save any existing weights string before doing so otherwise it will be erased.

**Comment by memoakten** [comment]
oh awesome, thanks! It wasn't a critical error for me, because once you explained the behaviour, I could just start the transition at frame1 instead of frame0. But for someone new coming onto this node, and wanting to start a transition immediately, this will surely save some headaches!
